### ISSUE TITLE
"CCT out of range" Warning Upon CRI Computation

### ISSUE THREAD

**Issue by michaelweinold** [ksmet1977/luxpy#11]
The computation of the CRI associated with [the spectral power distribution of a red LED](https://github.com/wasserwaage/CRI/blob/master/Data/output/test/spd_plot.png)

`cri = luxpy.color.cri.spd_to_cri(spd)
`

gives me a warning

`Warning: xyz_to_cct_HA(): one or more CCTs out of range! --> (CCT < 3 kK,  CCT >800 kK) coded as (-1, NaN) 's`

File:
[ndarray file containing SPD](https://github.com/wasserwaage/CRI/blob/master/Data/output/test/spd) (load using Pickle)

**Comment by ksmet1977** [comment]
Yes,This is because as it says cct calculations are only valid within a certain range. For this method this is within the range specified in the message.In other words, cct of e.g. a green light makes no sense (duv too large) or if it is outside a certain cct range (for this approximation method).regards,KevinSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Michael <notifications@github.com> Date: 20/12/19  11:02  (GMT+01:00) To: ksmet1977/luxpy <luxpy@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [ksmet1977/luxpy] "CCT out of range" Warning Upon CRI Computation (#11) The computation of the CRI associated with the spectral power distribution of a red LED
cri = luxpy.color.cri.spd_to_cri(spd) 
gives me a warning
Warning: xyz_to_cct_HA(): one or more CCTs out of range! --> (CCT < 3 kK,  CCT >800 kK) coded as (-1, NaN) 's
File:
ndarray file containing SPD (load using Pickle)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ksmet1977/luxpy/issues/11?email_source=notifications\u0026email_token=ACS4LX6CQJFXRSVPAPEJTWTQZSJ4NA5CNFSM4J53S56KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IB5SQGQ",
"url": "https://github.com/ksmet1977/luxpy/issues/11?email_source=notifications\u0026email_token=ACS4LX6CQJFXRSVPAPEJTWTQZSJ4NA5CNFSM4J53S56KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IB5SQGQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ksmet1977** [comment]
So, because CCT is not defined for a colored light, such as a red led, no reference spectrum can be calculated and thus also no CRI. CRI is only valid for white light sources!Hope this helps.regards,KevinSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Michael <notifications@github.com> Date: 20/12/19  11:02  (GMT+01:00) To: ksmet1977/luxpy <luxpy@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [ksmet1977/luxpy] "CCT out of range" Warning Upon CRI Computation (#11) The computation of the CRI associated with the spectral power distribution of a red LED
cri = luxpy.color.cri.spd_to_cri(spd) 
gives me a warning
Warning: xyz_to_cct_HA(): one or more CCTs out of range! --> (CCT < 3 kK,  CCT >800 kK) coded as (-1, NaN) 's
File:
ndarray file containing SPD (load using Pickle)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ksmet1977/luxpy/issues/11?email_source=notifications\u0026email_token=ACS4LX6CQJFXRSVPAPEJTWTQZSJ4NA5CNFSM4J53S56KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IB5SQGQ",
"url": "https://github.com/ksmet1977/luxpy/issues/11?email_source=notifications\u0026email_token=ACS4LX6CQJFXRSVPAPEJTWTQZSJ4NA5CNFSM4J53S56KYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IB5SQGQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ksmet1977** [comment]
Non-issue as CCT is not valid for colored sources (see replies above).
