### ISSUE TITLE
Can't read ies/ldt 

### ISSUE THREAD

**Issue by seghier** [ksmet1977/luxpy#15]
Hello, i can't read ies or ldt file, why this error?

![image](https://user-images.githubusercontent.com/6026588/112165821-60a80200-8bef-11eb-82c6-cd98054c6660.png)

**Comment by ksmet1977** [comment]
Hi there,
You need to use either  `'max'` or `'I0'` strings as input to the `normalize` argument, as mention in the docstring:
 ````
:normalize:
        | 'I0', optional
        | If 'I0': normalize LID to intensity at (theta,phi) = (0,0)
        | If 'max': normalize to max = 1.
```

**Comment by seghier** [comment]
Thanks, i tried but always different errors

```
import luxpy as lx

file = "C://Users//archi//Downloads//SunLuminaireElectricMarch2014.IES"
#file = "C://Users//archi//Desktop//maxwell scene test//erco_33499000_1xqt32_230w.ldt"


#lx.iolidfiles.read_lamp_data(file,1.0,0,'I0',True)

lx.toolboxes.iolidfiles.read_lamp_data(file,1.0,0,'max',True)
```

```
C:\Python37\python.exe "C:/Users/archi/Dropbox/Maxwell tool/player/ra.py"
Traceback (most recent call last):
  File "C:/Users/archi/Dropbox/Maxwell tool/player/ra.py", line 9, in <module>
    lx.toolboxes.iolidfiles.read_lamp_data(file,1.0,0,'max',True)
  File "C:\Python37\lib\site-packages\luxpy\toolboxes\iolidfiles\io_lid_files.py", line 93, in read_lamp_data
    verbosity = verbosity, normalize = normalize)
  File "C:\Python37\lib\site-packages\luxpy\toolboxes\iolidfiles\io_lid_files.py", line 292, in read_IES_lamp_data
    IES = _complete_ies_lid(IES, lamp_h_type = IES['lamp_h_type'])
  File "C:\Python37\lib\site-packages\luxpy\toolboxes\iolidfiles\io_lid_files.py", line 304, in _complete_ies_lid
    IES['values'] = np.matlib.repmat(IES['candela_2d'],4,1)
  File "C:\Python37\lib\site-packages\numpy\__init__.py", line 304, in __getattr__
    "{!r}".format(__name__, attr))
AttributeError: module 'numpy' has no attribute 'matlib'

Process finished with exit code 1
```
------------------------
![image](https://user-images.githubusercontent.com/6026588/112207782-d6c05f00-8c17-11eb-8ae3-029193330a30.png)

![image](https://user-images.githubusercontent.com/6026588/112207905-fe172c00-8c17-11eb-9d59-903010e662a5.png)

**Comment by ksmet1977** [comment]
Hi,
First error is caused due to some change to numpy, I guess. One used to be
able to call numpy.matlib.repmat() directly (i.e. matlib was imported into
the numpy namespace). Now (or at least some numpy versions) one needs to
import it separately. I changed that behavior in luxpy a while back, but
apparently missed one call to matlib.repmat().
I corrected that now. So you can update luxpy from github (later I'll
update pypi by uploading a new version). For now, at command line just do
(make sure git is installed and on windows path):
pip install git+https://www.github.com/ksmet1977/luxpy -U

The other error is because you entered 'IO', not 'I0' (should be letter I
and number zero, not letter I and letter O).
If you happen to come across any other bugs, please let me know. Thanks for
using luxpy.

regards,
Kevin

Op di 23 mrt. 2021 om 20:41 schreef seghier ***@***.***>:

**Comment by seghier** [comment]
Thank you , i update it now 
I will try again

**Comment by seghier** [comment]
Thank you work fine now with IES file but there is an error with LDT

![image](https://user-images.githubusercontent.com/6026588/112217851-4a1b9e00-8c23-11eb-81bd-66a7e0e44a29.png)

This is the file if you want check it:

https://www.dropbox.com/s/q64o5qpx9qcx3ph/erco_33499000_1xqt32_230w.ldt?dl=0

**Comment by seghier** [comment]
And please how to get **Luminous intensities**? this would be very usefull to draw **polar curves**

![image](https://user-images.githubusercontent.com/6026588/112224030-04fb6a00-8c2b-11eb-9e42-da946d9f379b.png)

**Comment by ksmet1977** [comment]
The luminous intensities are stored in the 'candela_values' (as read from
file) and in 'candela_2d' (or 'values'). The latter keys contain normalized
candela values (as specified by normalize keyword; I've added option 'none'
for this so that the values will be as read from the file) as a 2d-array
with the rows referring to phi and columns to theta angles.
In 'map' you will find 'thetas', 'phis' and 'values'. These are the angles
and candela values (again normalized), but with the values to full ranges
[0,180] and [0,360] depending on symmetry specified in the file ('Isym' for
LDT files). Your file has 'Isym' 2 which I have not supported yet (I only
needed 'Isym' 4 for the project that I originally created this code for;
when I find the time I might update the code; not sure when though). I've
also changed the code to not raise an error on this, just a warning, so you
can still use it.
regards,
Kevin

Op di 23 mrt. 2021 om 22:57 schreef seghier ***@***.***>:
